@def F_YF begin #(V, U, Ax, r, SA)		# front tire force

  if length(Ax) != 1
    Fyf = zeros(Float64, (length(Ax),1))
    for ii in eachindex(Ax)
      Fyf[ii] = ((PD2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)) - ((PE2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PE1)*(1 - PE3)*(((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1))/((((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)^2 + EP^2)^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)))))) + (PV2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PV1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)));
    end
  else
    Fyf = Float64
    Fyf = ((PD2*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*(FzF0 - (Ax - V*r)*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)) - ((PE2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PE1)*(1 - PE3)*(((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1))/((((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)^2 + EP^2)^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)))))) + (PV2*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PV1*(FzF0 - (Ax - V*r)*dFzx_coeff)));
  end
  Fyf
end

#=
  Fyf = zeros(Float64, (length(V),1))
  for ii in 1:length(V)
    Fyf[ii] = ((PD2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)) - ((PE2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PE1)*(1 - PE3)*(((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1))/((((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)^2 + EP^2)^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)))))) + (PV2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PV1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)));
  end
=#

#  ((PD2*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*(FzF0 - (Ax - V*r)*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)) - ((PE2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PE1)*(1 - PE3)*(((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1))/((((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)^2 + EP^2)^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)))))) + (PV2*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PV1*(FzF0 - (Ax - V*r)*dFzx_coeff)));
#=
  if !ODE_solve #isdefined(VehicleModels,:N)
		Fyf = zeros(Float64, (N+1,1))
		for ii in 1:N+1
			Fyf[ii] = ((PD2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)) - ((PE2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PE1)*(1 - PE3)*(((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1))/((((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)^2 + EP^2)^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[ii] + la*r[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff) + PH1)))))) + (PV2*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)^2 + PV1*(FzF0 - (Ax[ii] - V[ii]*r[ii])*dFzx_coeff)));
		end
	else
		Fyf = Float64
		Fyf = ((PD2*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*(FzF0 - (Ax - V*r)*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)) - ((PE2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PE1)*(1 - PE3)*(((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1))/((((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)^2 + EP^2)^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)))))) + (PV2*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PV1*(FzF0 - (Ax - V*r)*dFzx_coeff)));
	end
	Fyf
  =#
