@def F_YF begin #(V, U, Ax, r, SA)		# front tire force
  if !ODE_solve #isdefined(VehicleModels,:N)
		Fyf = zeros(Float64, (N+1,1))
		for i in 1:N+1
			Fyf[i] = ((PD2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[i] + la*r[i])/(U[i]+EP)) - SA[i]) + PH2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1)) - ((PE2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff) + PE1)*(1 - PE3)*(((atan((V[i] + la*r[i])/(U[i]+EP)) - SA[i]) + PH2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1))/((((atan((V[i] + la*r[i])/(U[i]+EP)) - SA[i]) + PH2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1)^2 + EP^2)^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[i] + la*r[i])/(U[i]+EP)) - SA[i]) + PH2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V[i] + la*r[i])/(U[i]+EP)) - SA[i]) + PH2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1)))))) + (PV2*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PV1*(FzF0 - (Ax[i] - V[i]*r[i])*dFzx_coeff)));
		end
	else
		Fyf = Float64
		Fyf = ((PD2*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*(FzF0 - (Ax - V*r)*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)) - ((PE2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PE1)*(1 - PE3)*(((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1))/((((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)^2 + EP^2)^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzF0 - (Ax - V*r)*dFzx_coeff))^2 + EP^2)^(0.5))*0.001)+EP))*((atan((V + la*r)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*r)*dFzx_coeff) + PH1)))))) + (PV2*(FzF0 - (Ax - V*r)*dFzx_coeff)^2 + PV1*(FzF0 - (Ax - V*r)*dFzx_coeff)));
	end
	Fyf
end
