function F_YR(V, U, Ax, Yaw, SA)
	# rear tire force
	if isdefined(:N)
		F_YR = zeros(Float64, (N+1,1))
		for i in 1:N+1
			F_YR[i] = ((PD2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V[i] - lb*Yaw[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff) + PH1)) - ((PE2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff) + PE1)*(1 - PE3*(((atan((V[i] - lb*Yaw[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff) + PH1))/((((atan((V[i] - lb*Yaw[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff) + PH1)^2 + EP^2)^(0.5))))*((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V[i] - lb*Yaw[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V[i] - lb*Yaw[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff) + PH1)))))) + (PV2*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)^2 + PV1*(FzR0 + (Ax[i] - V[i]*Yaw[i])*dFzx_coeff)));
		end
	else
		i = 1;
		F_YR = Float64
		F_YR = ((PD2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V - lb*Yaw)/(U+EP))) + PH2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff) + PH1)) - ((PE2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff) + PE1)*(1 - PE3*(((atan((V - lb*Yaw)/(U+EP))) + PH2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff) + PH1))/((((atan((V - lb*Yaw)/(U+EP))) + PH2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff) + PH1)^2 + EP^2)^(0.5))))*((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V - lb*Yaw)/(U+EP))) + PH2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V - lb*Yaw)/(U+EP))) + PH2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff) + PH1)))))) + (PV2*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)^2 + PV1*(FzR0 + (Ax - V*Yaw)*dFzx_coeff)));
	end

	F_YR
end
