@def F_YR begin #(V, U, Ax, r, SA) # rear tire force
	if !ODE_solve #isdefined(VehicleModels,:N)
		Fyr = zeros(Float64, (N+1,1))
		for i in 1:N+1
			Fyr[i] = ((PD2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V[i] - lb*r[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1)) - ((PE2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff) + PE1)*(1 - PE3*(((atan((V[i] - lb*r[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1))/((((atan((V[i] - lb*r[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1)^2 + EP^2)^(0.5))))*((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V[i] - lb*r[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V[i] - lb*r[i])/(U[i]+EP))) + PH2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff) + PH1)))))) + (PV2*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)^2 + PV1*(FzR0 + (Ax[i] - V[i]*r[i])*dFzx_coeff)));
		end
	else
		Fyr = Float64
		Fyr = ((PD2*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*(FzR0 + (Ax - V*r)*dFzx_coeff))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V - lb*r)/(U+EP))) + PH2*(FzR0 + (Ax - V*r)*dFzx_coeff) + PH1)) - ((PE2*(FzR0 + (Ax - V*r)*dFzx_coeff) + PE1)*(1 - PE3*(((atan((V - lb*r)/(U+EP))) + PH2*(FzR0 + (Ax - V*r)*dFzx_coeff) + PH1))/((((atan((V - lb*r)/(U+EP))) + PH2*(FzR0 + (Ax - V*r)*dFzx_coeff) + PH1)^2 + EP^2)^(0.5))))*((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V - lb*r)/(U+EP))) + PH2*(FzR0 + (Ax - V*r)*dFzx_coeff) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*r)*dFzx_coeff))))/(((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)) + ((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)))/(((PD2*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PD1*PC1*(FzR0 + (Ax - V*r)*dFzx_coeff))^2+EP^2)^(0.5))*0.001)+EP))*((atan((V - lb*r)/(U+EP))) + PH2*(FzR0 + (Ax - V*r)*dFzx_coeff) + PH1)))))) + (PV2*(FzR0 + (Ax - V*r)*dFzx_coeff)^2 + PV1*(FzR0 + (Ax - V*r)*dFzx_coeff)));
	end
	Fyr
end
